- name: Wait for systems to boot up
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait up to 300 seconds
      wait_for_connection:
        delay: 3
        sleep: 5
        timeout: 300


- name: Setup SQL Always-On Cluster
  hosts: all
  gather_facts: true  
  become: true
  roles:
    - ansible_role_winsql



