ansible_connection: ssh
ansible_shell_type: powershell

# It would be nice if we could programatically define this list of letters
# in python you can use the ord() and char() functions to convert into ascii codes
# and numerically iterate. However, Ansible doesn't nativley implement these fns 
# so this is the easiest way...

letters: ['e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

SQL-Remote-port: 1433
AG-Endpoint-port: 5022

db_script: db_script
db_script_path:  '%USERPROFILE%\ansible.db_script'
cluster_ip_path: '%USERPROFILE%\ansible.cluster_ip'

windows_cluster: null