# 
# In the next section we do some basic setup on the VMs and
# install Choco and then MS SQL and MGMT tools
#


# Install Failover cluster feature + tools

- name: Install Failover-Clustering with sub features and management tools
  ansible.windows.win_feature:
    name: Failover-Clustering
    state: present
    include_sub_features: true
    include_management_tools: true
    
# This shouldn't be needed, but sometimes failover clustering tools are
# not installed by ansible.windows.win_feature     
    
- name: Explicitly ensure failover clustering mgmt tools are installed
  ignore_errors: true
  ansible.windows.win_shell: |
    Install-WindowsFeature -name FailOver-Clustering -IncludeManagementTools       


# Install MPIO and set up for iSCSI volumes

- name: Install Multipath IO
  ansible.windows.win_feature:
    name: Multipath-IO
    state: present

- name: Reboot 
  ansible.windows.win_reboot: 

- name: Configure MultiPath IO
  ansible.windows.win_shell: |
    Enable-MSDSMAutomaticClaim -BusType iSCSI
    Set-MPIOSetting -CustomPathRecovery Enabled -NewPathRecoveryInterval 20 -NewRetryCount 60 -NewPDORemovePeriod 60 -NewPathVerificationPeriod 30 -NewDiskTimeout 60


# Get choco

- name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
  win_chocolatey:
    name: chocolatey   

   
    
# Install the MS-SQL Server Dev Edition from the Choco catalogue

- name: Get hostname (computer name)
  ansible.windows.win_shell: |
    [System.Net.Dns]::GetHostName()
  register: computerName_raw
  
- name: Trim computerName string
  set_fact:
    computerName: "{{ computerName_raw.stdout | trim }}"
    cacheable: true       
 
- name: Install SQL Server 2022
  win_chocolatey:
    name: sql-server-2022
    state: present
    package_params: /SQLSYSADMINACCOUNTS:{{ computerName }}\{{ sysadmin_user }}
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0  
  
  
# Install SQL mamagement studio, etc.      

- name: Install SQL Mgmt Tools
  win_chocolatey:
    name: sql-server-management-studio
    state: present   