# Now setup Windows Clustering, using the IP we stored from the extra adapter earlier

- name: Collect IP addresses from each host
  set_fact:
    ip_addresses: "{{ groups['sql'] | map('extract', hostvars, 'ansible_host') | list }}" 
    cacheable: true
    

- name: Get Cluster Details
  run_once: true
  ignore_errors: true  
  ansible.windows.win_shell: |
    (get-cluster).name    
  register: windows_cluster        
    

- name: Create Windows Cluster
  run_once: true
  ansible.windows.win_shell: |
    $my_ip_list = "{{ ip_addresses }}" | ConvertFrom-Json
    new-cluster -Name {{ 'sql_cluster' + '-' + deployment_id }} -Node $my_ip_list -AdministrativeAccessPoint Dns -StaticAddress {{ cluster_ip }}
  when: not windows_cluster.stderr == ""

- name: Enable AlwaysOn Avail Groups
  ansible.windows.win_shell: |
    foreach ($node in Get-ClusterNode) {Enable-SqlAlwaysOn -ServerInstance $node -Force}  
  register: always_on_ag  
  

- name: Restart the SQL Service
  ansible.windows.win_shell: | 
    Restart-Service MSSQLSERVER