# Now setup Windows Clustering, using the IP we stored from the extra adapter earlier

- name: Collect IP addresses from each host
  set_fact:
    ip_addresses: "{{ groups['sql'] | map('extract', hostvars, 'ansible_host') | list }}" 
    

- name: Create Windows Cluster
  run_once: true
  ansible.windows.win_shell: |
    $my_ip_list = "{{ ip_addresses }}" | ConvertFrom-Json
    new-cluster -Name {{ 'sql_cluster' + '-' + deployment_id }} -Node $my_ip_list -AdministrativeAccessPoint Dns -StaticAddress {{ cluster_ip }}

- name: Enable AlwaysOn Avail Groups
  ansible.windows.win_shell: |
    foreach ($node in Get-ClusterNode) {Enable-SqlAlwaysOn -ServerInstance $node -Force}  
    Restart-Service MSSQLSERVER

 