# We let the SQL serivce access the drives we've created.
# As we're not in production, this will do for now, but ideally
# we should create a separate user for SQL, etc.

- name: Set drive/folder permissions for the sql service
  ansible.windows.win_acl:
    user: NT Service\MSSQLSERVER
    path: "{{ item.value + ':\' }}"
    rights: FullControl
    type: allow
    state: present
  loop: "{{ drive_mapping | dict2items }}"        


# Finally, we run the SQL script as passed in from VCF Automation
    
- name: Save the db scipt to a file
  ansible.windows.win_template:
    src: db_script
    dest: "{{ db_script_path }}" 
    
- name: Convert %USERPROFILE% to env:userprofile for powershell
  ansible.builtin.set_fact:
    db_script_ps_path: "{{ db_script_path | replace('%', '') | lower | regex_replace('userprofile', '\\$env:userprofile') }}"

- name: Display the converted string
  debug:
    msg: "Converted string: {{ db_script_ps_path }}" 

- name: Run DB script on first host
  run_once: true
  ansible.windows.win_shell: |
    sqlcmd -S 127.0.0.1 -E -i "{{ db_script_ps_path }}"
    